
##### IP
POST http://localhost:8000/ip
Content-Type: application/json

{}

##### LIST
POST http://localhost:8000/list
Content-Type: application/json

{}

##### REGISTER WEBHOOK
POST http://localhost:8000/register
Content-Type: application/json

{
    "url" : "https://web.whatsapp.com/"
}

##### UPDATE WEBHOOK
POST http://localhost:8000/update
Content-Type: application/json

{
    "id" : "lODUaTXJCroPNPPI",
    "url" : "https://web.whatsapp.com/"
}

#####
POST http://localhost:3000/api/webhooks/trigger
Content-Type: application/json

{
    "ipAddress": "::ffff:127.0.0.1"
}
