
##### IP
POST http://localhost:8000/ip
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYyNjQ0NjY4OH0.-Pcjh4Ke4qEsj13oF9GmLiP80J_Y5pezFfTeDtonXks

{}

##### LIST
POST http://localhost:8000/list
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYyNjQ0NjY4OH0.-Pcjh4Ke4qEsj13oF9GmLiP80J_Y5pezFfTeDtonXks

{}

##### REGISTER WEBHOOK
POST http://localhost:8000/register
Content-Type: application/json

{
    "url" : "https://web.whatsapp.com/"
}

##### UPDATE WEBHOOK
POST http://localhost:8000/update
Content-Type: application/json

{
    "id" : "lODUaTXJCroPNPPI",
    "url" : "https://web.whatsapp.com/"
}

##### PURGE WEBHOOK
POST http://localhost:8000/delete
Content-Type: application/json

{
    "id" : "mGeThLAcoXLNqTic"
}


##### Sign JWT
POST http://localhost:8000/sign-jwt
Content-Type: application/json

{
    "email" : "admin@admin.com"
}

#####
GET http://localhost:3000/api/webhooks/trigger/OjpmZmZmOjEyNy4wLjAuMQ==
