
##### IP
POST http://localhost:8000/ip
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYyNjQ0NjY4OH0.-Pcjh4Ke4qEsj13oF9GmLiP80J_Y5pezFfTeDtonXks

{}

##### LIST
POST http://localhost:8000/list
Content-Type: application/json
token: eyJhbGdciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRpdnlhbnNoQGdtYWlsLmNvbSIsImlhdCI6MTYyNjUxMjQ5NH0.OgJwihAc1iwoZ43namaMPEolWFSQnoCE6ny2UnSUmXg

{}

##### REGISTER WEBHOOK
POST http://localhost:8000/register
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRpdnlhbnNoQGdtYWlsLmNvbSIsImlhdCI6MTYyNjUxMjQ5NH0.OgJwihAc1iwoZ43namaMPEolWFSQnoCE6ny2UnSUmXg

{
    "url" : "http://localhost:8000/trigger"
}

##### UPDATE WEBHOOK
POST http://localhost:8000/update
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYyNjQ0NjY4OH0.-Pcjh4Ke4qEsj13oF9GmLiP80J_Y5pezFfTeDtonXks

{
    "id" : "lODUaTXJCroPNPPI",
    "url" : "https://web.whatsapp.com/"
}

##### PURGE WEBHOOK
POST http://localhost:8000/delete
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYyNjQ0NjY4OH0.-Pcjh4Ke4qEsj13oF9GmLiP80J_Y5pezFfTeDtonXks

{
    "id" : "5OS8wTRYdQryGdcp"
}


##### Sign JWT
POST http://localhost:8000/sign-jwt
Content-Type: application/json

{
    "email" : "divyansh@gmail.com"
}

#####
GET http://localhost:3000/api/webhooks/trigger/OjpmZmZmOjEyNy4wLjAuMQ==
